### ISSUE TITLE
This is not issue :D

### ISSUE THREAD

**Issue by zerOnepal** [ArtifexSoftware/ghostpdl-downloads#1]
Thanks @chris-liddell, @mwoehrmann (and those envolved) for bringing this to github.

Hope, you you people would push some docs like: _how to compile and stuffs regarding the dependencies._

**Comment by robinwatts** [comment]
What, you mean like all the documentation linked from http://www.ghostscript.com/ and included with the source code?

**Comment by zerOnepal** [comment]
Something equivalent to http://www.linuxfromscratch.org/blfs/view/7.8/pst/gs.html
@robinwatts 
life would be much easier for all. thanks
