### ISSUE TITLE
Source code archives contain no source code

### ISSUE THREAD

**Issue by drakecooperdigital** [ArtifexSoftware/ghostpdl-downloads#2]
The files at:
https://github.com/ArtifexSoftware/ghostpdl-downloads/archive/gs919.zip
and
https://github.com/ArtifexSoftware/ghostpdl-downloads/archive/gs919.tar.gz
don't appear to contain any source code, only the README.md file.

Where can one download the source?

Thanks
Joe

**Comment by chris-liddell** [comment]
The canonical Ghostscript downloads are accessed here:
http://ghostscript.com/download/

We're just using github as a downloads server (for now, anyway).
