### ISSUE TITLE
Configure option --disable-sse2 doesn't work in 9.19.

### ISSUE THREAD

**Issue by grubba** [ArtifexSoftware/ghostpdl-downloads#3]
The gcc bundled with Solaris 10/amd64 defines __SSE__, but does not have the corresponding types (__m128 et al), which causes openjpeg/src/lib/openjp2/dwt.c to fail to compile.

From reading autoconf.ac, it looks like the option --disable-sse2 is intended to disable the use of sse2, and it does clear HAVE_SSE2, which in turn causes JPX_SSE_CFLAGS to be set to -U__SSE__.
There's however no further use of JPX_SSE_CFLAGS, so the option doesn't affect the build.

I suggest adding an AC_SUBST(JPX_SSE_CFLAGS) to configure.ac, and appending @JPX_SSE_CFLAGS@ to the definition of JPX_CFLAGS in Makefile.in.

**Comment by chris-liddell** [comment]
Please see http://bugs.ghostscript.com/show_bug.cgi?id=697138

for tracking of this issue.
