### ISSUE TITLE
Missing output device?

### ISSUE THREAD

**Issue by adamdyson** [ArtifexSoftware/ghostpdl-downloads#4]
I'm looking for confirmation that the SVG device is a part of Ghostscript. The latest online documentation says that it is supported [https://ghostscript.com/doc/9.21/WhatIsGS.htm#GhostSVG](https://ghostscript.com/doc/9.21/WhatIsGS.htm#GhostSVG) however when I list the output device there is no mention of it?

I did come across this [bug report](https://bugs.ghostscript.com/show_bug.cgi?id=692527) which mentions at the end that this will become part of MuPDF? However the coumentation says its part of GhostPDL? Can someone kindly point me in the right direction for working with SVG.

**Comment by chris-liddell** [comment]
GhostSVG is *not* the SVG device, but is the SVG interpreter (as it says _quite_ clearly on the page to which you have linked), which was incomplete, is not longer distributed, and is considered deprecated. 

The SVG output *device* also deprecated some years ago, as it was also incomplete.
