### ISSUE TITLE
Compiling GhostPDL on RaspberryPi

### ISSUE THREAD

**Issue by RWAP** [ArtifexSoftware/ghostpdl-downloads#5]
Is there anything in GhostPDL which prevents it from working on ARM architecture used on the Raspberry Pi?

I have installed GhostPDL from sources and compiled it with:

```
apt-get install libcups2-dev libcupsimage2-dev
cd /tmp
wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs921/ghostpdl-9.21.tar.gz
tar zxvf ghostpdl-9.21.tar.gz  
cd ghostpdl-9.21
./autogen.sh
./configure
make
make install
```

However, when I try the command:
`gs -sDEVICE=printer -dNOPAUSE W495.PCL -c quit;`

using one of the test files from http://www.pcltools.com/propthlp.php, I get an error after the initial GhostPDL output - when it starts processing the page, it reports: 
\ undefined

Not very helpful.

**Comment by chris-liddell** [comment]
Well, Ghostcript is a Postscript/PDF interpreter, and you appear to be trying to interpret a PCL file. You might get better results if you use the PCL interpreter - gpcl6.

**Comment by RWAP** [comment]
Sorry - I thought GhostPDL (which is what I thought I donwloaded as above) interpreted postscript, PCL and PDF ?

**Comment by RWAP** [comment]
Ah - now I think I can see what you mean - the GhostPDL offers the program gpcl6 and gs so I need to change the line to:

`gpcl6 -sDEVICE=printer -dNOPAUSE W495.PCL -c quit;`

Sorry - I thought it was just one program which would automatically pick up the source type.

**Comment by chris-liddell** [comment]
The combined binary that included all the languages had fundamental problems, so we're in the process of re-engineering it to resolve those. In the meantime, we prefer folks not to use it, hence it doesn't get built.
