### ISSUE TITLE
9.21 windows binaries are unavailable

### ISSUE THREAD

**Issue by KodjoSuprem** [ArtifexSoftware/ghostpdl-downloads#6]
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs921

propose 9.22 windows binaries. 
Is it a mistake?

I would like the 9.21 binaries

**Comment by chris-liddell** [comment]
Sorry, I must have accidentally replaced them during the 9.22 release. I've put the 9.21 binaries back, now. Note that we *strongly* recommend using the newest version.
